version: '3.3'

services:
  backend-laravel:
    build: docker/php
    container_name: backend-laravel
    working_dir: /var/www/
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./backend/:/var/www/
      - ./docker/php/logs/:/var/log/php/
    depends_on:
      - mysql-laravel
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
      PHP_IDE_CONFIG: serverName=PHPSTORM

  nginx-laravel:
    image: nginx:1.21.1
    container_name: nginx-laravel
    ports:
      - 85:80
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/certs/:/etc/nginx/certs
      - ./docker/nginx/htpasswd/:/etc/nginx/htpasswd
      - ./docker/nginx/templates/:/etc/nginx/templates
      - ./docker/nginx/logs/:/var/log/nginx
      - ./backend/:/var/www
    depends_on:
      - backend-laravel
    environment:
      NGINX_UPSTREAM: backend-laravel:9000

  mysql-laravel:
    image: mysql:8.0.26
    container_name: mysql-laravel
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/mysql/:/var/lib/mysql:rw
      - ./docker/mysql/logs/:/var/log/mysql:rw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=000000
      - MYSQL_DATABASE=docker-boilerplate
      - MYSQL_USER=docker-boilerplate
      - MYSQL_PASSWORD=docker-boilerplate
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      - PMA_ARBITRARY=1

  #https://hub.docker.com/r/bitnami/rabbitmq
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_PASSWORD=123123
      - RABBITMQ_USERNAME=root
    ports:
      - 5672:5672 # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 123123
    ports:
     - "6379:6379"
  
  # docker exec -it supervisor /bin/sh  
  supervisor:
    build:
      context: .
      dockerfile: docker/supervisor/supervisor.dockerfile
    container_name: supervisor
    volumes:
      - ./backend:/var/www
    depends_on:
      - backend-laravel
      - mysql-laravel

  # https://github.com/aschmelyun/laravel-scheduled-tasks-docker
  cron:
    build:
      context: .
      dockerfile: cron.dockerfile
    container_name: cron
    volumes:
      - ./backend/:/var/www
